### ISSUE TITLE
Is it still maintained?

### ISSUE THREAD

**Issue by Mr-Markus** [creativetimofficial/vuetify-material-dashboard#30]
Hi @dragosct10 ,

what is the reason that your last commit on code was in October 2018 here e7fdc873594244c9acc3f953e8bab1077375970d ?

It seems that it is not further developed, isn't it?

Are you caring about vue.js in generell any more or will other frameworks be more focused by @creativetimofficial?

Thanks!

**Comment by dragosct10** [comment]
Hi, @Mr-Markus! Thank you for using our products. You are right for the moment the product it's not maintained because it was developed by an external team from vuetify and we are in discussion with them to continue maintaining this product and for future products. Anyway, for sure in the next period, we will have updates on the repo and also we will have the pro version and other products. We are caring about and we are focused on the vuejs.

Thank you for your understanding!

Regards, 
Dragos

**Comment by Mr-Markus** [comment]
Hi @dragosct10 ,

thanks for your quick reply. I understand what you mean and will looking forward for a Pro version of the vuetify template :-)

Best
Markus
